### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by KasraIDK** [vivyir/femtorinth#1]
i dont get it

**Comment by Spixa** [comment]
same

**Comment by vivyir** [comment]
femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?

**Comment by Spixa** [comment]
no

**Comment by KasraIDK** [comment]
> femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
Of course i know i literally introduced it to you ong i am offended this second

**Comment by KasraIDK** [comment]
> > femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
> > Of course i know i literally introduced it to you ong i am offended this second

How did i fuck up the quote

**Comment by vivyir** [comment]
> no

it is an open source and easy to use modding platform with a conveniently modern design

**Comment by vivyir** [comment]
> > > femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
> > > Of course i know i literally introduced it to you ong i am offended this second
> 
> How did i fuck up the quote

i also fucked it dont worry

**Comment by KasraIDK** [comment]
> > > > femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
> > > > Of course i know i literally introduced it to you ong i am offended this second
> > 
> > 
> > How did i fuck up the quote
> 
> i also fucked it dont worry

Github bad lets go to the other hub

**Comment by Spixa** [comment]
Ok thanks now what does it have to do with this repository also how reply

**Comment by vivyir** [comment]
> > > > > femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
> > > > > Of course i know i literally introduced it to you ong i am offended this second
> > > 
> > > 
> > > How did i fuck up the quote
> > 
> > 
> > i also fucked it dont worry
> 
> Github bad lets go to the other hub

my man

**Comment by KasraIDK** [comment]
> Ok thanks now what does it have to do with this repository also how reply

Idk how reply also idk what this still is this issue is yet to be resolved

**Comment by Spixa** [comment]
> > > > > femtorinth, mates, do yall know the popular modding platform called [Modrinth](https://modrinth.com)?
> > > > > Of course i know i literally introduced it to you ong i am offended this second
> > > 
> > > 
> > > How did i fuck up the quote
> > 
> > i also fucked it dont worry
> 
> Github bad lets go to the other hub

lets go to grubhub

**Comment by vivyir** [comment]
> Ok thanks now what does it have to do with this repository also how reply

this is a rust library to use modrinth's api, are you sold????

**Comment by KasraIDK** [comment]
> > Ok thanks now what does it have to do with this repository also how reply
> 
> this is a rust library to use modrinth's api, are you sold????

Maybe, does it integrate with Microsoft 365?

**Comment by Spixa** [comment]
> > Ok thanks now what does it have to do with this repository also how reply
> 
> this is a rust library to use modrinth's api, are you sold????

This is Xi Jinping and Zhong Xina has informed me you are selling people. Your execution day is October the 21st 2021, 17:30 EST

**Comment by vivyir** [comment]
> > > Ok thanks now what does it have to do with this repository also how reply
> > 
> > 
> > this is a rust library to use modrinth's api, are you sold????
> 
> Maybe, does it integrate with Microsoft 365?

yes, it also has discord rich presence and xbox live integration

**Comment by vivyir** [comment]
> > > Ok thanks now what does it have to do with this repository also how reply
> > 
> > 
> > this is a rust library to use modrinth's api, are you sold????
> 
> This is Xi Jinping and Zhong Xina has informed me you are selling people. Your execution day is October the 21st 2021, 17:30 EST

p;leas.e noo tha'ts the rust 2021 edition release date i think, is it??

**Comment by Spixa** [comment]
> > > > Ok thanks now what does it have to do with this repository also how reply
> > > 
> > > 
> > > this is a rust library to use modrinth's api, are you sold????
> > 
> > Maybe, does it integrate with Microsoft 365?
> 
> yes, it also has discord rich presence and xbox live integration

plees wrighte it for nativ windows only i hat linux >:(((((

**Comment by KasraIDK** [comment]
> > > > Ok thanks now what does it have to do with this repository also how reply
> > > 
> > > 
> > > this is a rust library to use modrinth's api, are you sold????
> > 
> > 
> > Maybe, does it integrate with Microsoft 365?
> 
> yes, it also has discord rich presence and xbox live integration

Trick question I hAte FemtorintH nOw
Dont Mind THe randOM capitaLizAtiOn gboaRd Is Ass

**Comment by vivyir** [comment]
> > > > > Ok thanks now what does it have to do with this repository also how reply
> > > > 
> > > > 
> > > > this is a rust library to use modrinth's api, are you sold????
> > > 
> > > 
> > > Maybe, does it integrate with Microsoft 365?
> > 
> > 
> > yes, it also has discord rich presence and xbox live integration
> 
> Trick question I hAte FemtorintH nOw Dont Mind THe randOM capitaLizAtiOn gboaRd Is Ass

because of this i am going to give you the `bad first issue` label right now istg

**Comment by Spixa** [comment]
> > > > Ok thanks now what does it have to do with this repository also how reply
> > > 
> > > 
> > > this is a rust library to use modrinth's api, are you sold????
> > 
> > This is Xi Jinping and Zhong Xina has informed me you are selling people. Your execution day is October the 21st 2021, 17:30 EST
> 
> p;leas.e noo tha'ts the rust 2021 edition release date i think, is it??

Zho Chon is your executioner, your last meal is bing chilling (ice cream in chinese). please mark your last words here because we dont have time tmr

**Comment by vivyir** [comment]
> > > > > Ok thanks now what does it have to do with this repository also how reply
> > > > 
> > > > 
> > > > this is a rust library to use modrinth's api, are you sold????
> > > 
> > > 
> > > This is Xi Jinping and Zhong Xina has informed me you are selling people. Your execution day is October the 21st 2021, 17:30 EST
> > 
> > 
> > p;leas.e noo tha'ts the rust 2021 edition release date i think, is it??
> 
> Zho Chon is your executioner, your last meal is bing chilling (ice cream in chinese). please mark your last words here because we dont have time tmr

my last words are: join modrinth, install rust, become rust programmer, ggwp

**Comment by KasraIDK** [comment]
I understand what this is now. Issue resolved, thanks.

**Comment by Spixa** [comment]
> > > > > > Ok thanks now what does it have to do with this repository also how reply
> > > > > 
> > > > > 
> > > > > this is a rust library to use modrinth's api, are you sold????
> > > > 
> > > > 
> > > > This is Xi Jinping and Zhong Xina has informed me you are selling people. Your execution day is October the 21st 2021, 17:30 EST
> > > 
> > > 
> > > p;leas.e noo tha'ts the rust 2021 edition release date i think, is it??
> > 
> > Zho Chon is your executioner, your last meal is bing chilling (ice cream in chinese). please mark your last words here because we dont have time tmr
> 
> my last words are: join modrinth, install rust, become rust programmer, ggwp

President Xin Jinping has requested you to delete this; otherwise your last words are gonna be modified to:
"Code in JavaScript, join curseforge and uninstall rust and delete firefox"

**Comment by Spixa** [comment]
President has committed suicide because you didn't answer

**Comment by vivyir** [comment]
> President has committed suicide because you didn't answer

gg ez

**Comment by KasraIDK** [comment]
Guys what is this again i forgor 💀

**Comment by KasraIDK** [comment]
i rember 😀
