### ISSUE TITLE
`Cargo.lock` file should not be committed

### ISSUE THREAD

**Issue by theRookieCoder** [vivyir/femtorinth#4]
[Rust documentation](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) specifies that
> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put `Cargo.lock` in your `.gitignore`

So the `Cargo.lock` should not be committed

**Comment by vivyir** [comment]
Thanks for bringing this to my attention! I've added it to `.gitignore` and also updated dependencies in `Cargo.toml` which is now published as v0.1.2!
